{"width":50,"height":50,"experience":80,
"level":[
{"reloadSpeed":4,"projectiles":1,"projectileName":"laser","icon":"concept.png","range":150,"damage":5,"cost":80,"score":3},
{"reloadSpeed":4,"projectiles":1,"projectileName":"laser","icon":"concept1.png","range":150,"damage":7,"cost":40,"score":1},
{"reloadSpeed":4,"projectiles":2,"projectileName":"laser","icon":"concept2.png","range":150,"damage":7,"cost":80,"score":3},
{"reloadSpeed":4,"projectiles":3,"projectileName":"laser","icon":"concept3.png","range":150,"damage":10,"cost":40,"score":2}
]}

