{"width":40,"height":40,
"level":[
{"reloadSpeed":4,"projectiles":1,"projectileName":"exampleProjectile","icon":"exampleTower.png","range":100,"damage":2,"cost":50},
{"reloadSpeed":4,"projectiles":1,"projectileName":"exampleProjectile","icon":"exampleTower1.png","range":100,"damage":5,"cost":60},
{"reloadSpeed":2,"projectiles":1,"projectileName":"exampleProjectile","icon":"exampleTower2.png","range":100,"damage":5,"cost":70}
]}
