{"width":40,"height":40,
"level":[
{"reloadSpeed":4,"projectiles":1,"projectileName":"exampleProjectile","icon":"repeater.png","range":100,"damage":2,"cost":50,"score":2},
{"reloadSpeed":4,"projectiles":1,"projectileName":"exampleProjectile","icon":"repeater2.png","range":100,"damage":5,"cost":60,"score":2},
{"reloadSpeed":2,"projectiles":1,"projectileName":"exampleProjectile","icon":"repeater3.png","range":100,"damage":5,"cost":70,"score":4}
]}
